os: linux
dist: trusty
sudo: false
compiler:
- clang
- gcc
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - php5
install:
- pip install --upgrade pip
- pip install tox-travis
- gem install rspec
- gem install simplecov || true
- gem install minitest
before_script:
- export PATH=${HOME}/.local/bin:${PATH}
- mkdir Build
- cd Build
- cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install
script:
- cmake --build . --target install && ctest -V
